/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.twitter.finagle.thrift.thrift;

public class Constants {

  /**
   * The following is from BigBrotherBird:
   *   http://j.mp/fZZnyD
   */
  public static final String WIRE_SEND = "ws";

  public static final String WIRE_RECV = "wr";

  public static final String WIRE_RECV_ERROR   = "Wire Receive Error";

  public static final String CLIENT_SEND = "cs";

  public static final String CLIENT_RECV = "cr";

  public static final String CLIENT_RECV_ERROR   = "Client Receive Error";

  public static final String SERVER_SEND = "ss";

  public static final String SERVER_RECV = "sr";

  public static final String SERVER_SEND_ERROR   = "Server Send Error";

  public static final String SERVER_ADDR = "sa";

  public static final String CLIENT_ADDR = "ca";

  public static final String CLIENT_SEND_FRAGMENT = "csf";

  public static final String CLIENT_RECV_FRAGMENT = "crf";

  public static final String SERVER_SEND_FRAGMENT = "ssf";

  public static final String SERVER_RECV_FRAGMENT = "srf";

}
